name: Build OSMesa Lib

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu:18.04
    container:
      image: ghcr.io/newchromantics/osmesa-env

    steps:
      - uses: actions/checkout@v2

      - name: Move into mesa folder
        run: cd mesa

      - name: Run Meson
        run: |
          /usr/local/bin/meson builddir \
          -Dplatforms=drm \
          -Dosmesa=gallium \
          -Dgallium-drivers=swrast \
          -Ddri-drivers=[] \
          -Dvulkan-drivers=[] \
          -Dglx=disabled

      - name: Run Ninja
        run: ninja -C builddir install

      - name: Upload Built Libs
        uses: actions/upload-artifact@v2
        with:
          name: OSMesa
          path: /usr/local/lib/x86_64-linux-gnu
